import type { ThemePack } from "./types";

export const snesPack: ThemePack = {
  id: "snes",
  name: "SNES",
  description: "Deep purple-black substrate, electric violet accents, four-button semantic color system. Hard-offset shadows, zero radius, scanline overlay, pixel-font hierarchy.",
  dark: {
    colors: {
      background:   "#1a1530",
      panel:        "#0f0c20",
      card:         "#241d3d",
      border:       "#3a3060",
      borderActive: "#9e7bff",
      primary:      "#9e7bff",
      primaryDeep:  "#6b4eb8",
      text:         "#e8e3ff",
      textDim:      "#a89bd6",
      textFaint:    "#7a6da8",
      textBright:   "#e8e3ff",
      success:      "#4eb84a",
      warning:      "#ffb73a",
      danger:       "#e84a4a",
      info:         "#5e9cff",
      shadow:       "#0c0a1c",
    },
    fonts: {
      heading: "'Press Start 2P', 'Courier New', monospace",
      body:    "'VT323', 'Courier New', monospace",
      mono:    "'JetBrains Mono', 'Courier New', monospace",
    },
    radius: {
      none: "0px",
      sm:   "0px",
      md:   "0px",
      lg:   "0px",
      full: "0px",
    },
    shadow: {
      card:      "3px 3px 0 0 #0c0a1c",
      cardHover: "4px 4px 0 0 #0c0a1c",
      glow:      "none",
    },
    motifs: {
      divider:         "notch",
      statusBarText:   "CARTDEX / PRESS START TO BEGIN",
      cardBorderWidth: "2px",
      scanlines:       true,
      scanlinesOpacity: "0.05",
    },
    googleFonts: [
      "Press Start 2P",
      "VT323",
      "JetBrains Mono:wght@400;500;600",
    ],
  },
  light: {
    colors: {
      background:   "#f4f1fb",
      panel:        "#ede8f7",
      card:         "#ffffff",
      border:       "#c4b8e8",
      borderActive: "#6b4eb8",
      primary:      "#6b4eb8",
      primaryDeep:  "#9e7bff",
      text:         "#1a1530",
      textDim:      "#5a4a8a",
      textFaint:    "#a89bd6",
      textBright:   "#1a1530",
      success:      "#2e7d2e",
      warning:      "#d4920a",
      danger:       "#c0302e",
      info:         "#2a62b8",
      shadow:       "#c4b8e8",
    },
    fonts: {
      heading: "'Press Start 2P', 'Courier New', monospace",
      body:    "'VT323', 'Courier New', monospace",
      mono:    "'JetBrains Mono', 'Courier New', monospace",
    },
    radius: {
      none: "0px",
      sm:   "0px",
      md:   "0px",
      lg:   "0px",
      full: "0px",
    },
    shadow: {
      card:      "3px 3px 0 0 #c4b8e8",
      cardHover: "4px 4px 0 0 #c4b8e8",
      glow:      "none",
    },
    motifs: {
      divider:         "notch",
      statusBarText:   "CARTDEX / PRESS START TO BEGIN",
      cardBorderWidth: "2px",
      scanlines:       false,
      scanlinesOpacity: "0",
    },
    googleFonts: [
      "Press Start 2P",
      "VT323",
      "JetBrains Mono:wght@400;500;600",
    ],
  },
};
