import type { ThemePack } from "./types";

export const tatooInePack: ThemePack = {
  id: "tatooine",
  name: "Tatooine",
  description: "Desert-warm substrate, sand-and-ochre palette, Orbitron/Rajdhani/Share Tech Mono type stack. Worn utilitarian feel with ambient glow and hologram hover. The default CartDex aesthetic.",
  dark: {
    colors: {
      background:   "#0d0a07",
      panel:        "#151009",
      card:         "#1a1208",
      border:       "#2a1f14",
      borderActive: "#8a7450",
      primary:      "#c4a46c",
      primaryDeep:  "#b5651d",
      text:         "#d4c4a0",
      textDim:      "#7a6b52",
      textFaint:    "#4a3d2a",
      textBright:   "#e8dcc4",
      success:      "#4a6b3a",
      warning:      "#c4a46c",
      danger:       "#8b3a3a",
      info:         "#4a7a9b",
      shadow:       "rgba(0,0,0,0.4)",
    },
    fonts: {
      heading: "'Orbitron', system-ui, sans-serif",
      body:    "'Rajdhani', system-ui, sans-serif",
      mono:    "'Share Tech Mono', 'Courier New', monospace",
    },
    radius: {
      none: "0px",
      sm:   "3px",
      md:   "6px",
      lg:   "10px",
      full: "9999px",
    },
    shadow: {
      card:      "0 0 0 0 transparent",
      cardHover: "0 0 20px rgba(196,164,108,0.15)",
      glow:      "0 0 20px rgba(196,164,108,0.15)",
    },
    motifs: {
      divider:         "rule",
      statusBarText:   "Holocron Archive System",
      cardBorderWidth: "1px",
      scanlines:       true,
      scanlinesOpacity: "0.03",
    },
    googleFonts: [
      "Orbitron:wght@400;500;600;700;800;900",
      "Rajdhani:wght@300;400;500;600;700",
      "Share Tech Mono",
    ],
  },
  light: {
    colors: {
      background:   "#f5efe0",
      panel:        "#e8dcc4",
      card:         "#faf5eb",
      border:       "#c8a877",
      borderActive: "#8a5e22",
      primary:      "#8a5e22",
      primaryDeep:  "#b5651d",
      text:         "#2a1f0e",
      textDim:      "#6b5233",
      textFaint:    "#a08060",
      textBright:   "#1a120b",
      success:      "#2e5c1e",
      warning:      "#8a5e22",
      danger:       "#7a2020",
      info:         "#2a5070",
      shadow:       "rgba(90,60,20,0.15)",
    },
    fonts: {
      heading: "'Orbitron', system-ui, sans-serif",
      body:    "'Rajdhani', system-ui, sans-serif",
      mono:    "'Share Tech Mono', 'Courier New', monospace",
    },
    radius: {
      none: "0px",
      sm:   "3px",
      md:   "6px",
      lg:   "10px",
      full: "9999px",
    },
    shadow: {
      card:      "0 0 0 0 transparent",
      cardHover: "0 0 12px rgba(90,60,20,0.15)",
      glow:      "0 0 12px rgba(90,60,20,0.15)",
    },
    motifs: {
      divider:         "rule",
      statusBarText:   "Holocron Archive System",
      cardBorderWidth: "1px",
      scanlines:       false,
      scanlinesOpacity: "0",
    },
    googleFonts: [
      "Orbitron:wght@400;500;600;700;800;900",
      "Rajdhani:wght@300;400;500;600;700",
      "Share Tech Mono",
    ],
  },
};
